import xgboost
import m2cgen as m2c
import os
import sys
import sklearn

# The model file is now the version-agnostic JSON format
MODEL_FILE = 'model.json'
OUTPUT_DIR = 'src'
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'xgb_model.h')

def transpile_model():
    """
    Loads a model from XGBoost's JSON format, transpiles it to C code,
    optimizes it for single-precision hardware, and saves it as a C header file.
    """
    print("--- XGBoost to C Transpilation for ESP32-S3 ---")
    print(f"  Python version: {sys.version}")
    print(f"  m2cgen version: {m2c.__version__}")
    print(f"  xgboost version: {xgboost.__version__}")
    print(f"  scikit-learn version: {sklearn.__version__}")
    print("-" * 40)

    # Ensure output directory exists
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        print(f"Created directory: '{OUTPUT_DIR}'")

    # 1. Load the trained model from the JSON file
    print(f"Attempting to load model from '{MODEL_FILE}'...")
    try:
        # Instantiate a classifier object first, then load the state into it.
        model = xgboost.XGBClassifier()
        model.load_model(MODEL_FILE)
    except FileNotFoundError:
        print(f"FATAL: Model file not found at '{MODEL_FILE}'.")
        print("Please ensure you have run the 'convert_model_format.py' script first.")
        return
    except Exception as e:
        print(f"An error occurred while loading the model: {e}")
        return
    print("Model loaded successfully.")

    # 2. Transpile model to C code
    print("Transpiling model to C code...")
    try:
        model_code_str = m2c.export_to_c(model)
    except Exception as e:
        print(f"FATAL: m2cgen failed to transpile the model.")
        print(f"Error: {e}")
        return

    # 3. Hardware Optimization: Replace 'double' with 'float'
    optimized_code_str = model_code_str.replace('double', 'float')
    print("Optimized code for single-precision FPU by replacing 'double' with 'float'.")

    # 4. Add include guard for safe inclusion in C/C++ projects
    final_code = f"""#ifndef XGB_MODEL_H
#define XGB_MODEL_H

// Automatically generated by m2cgen. DO NOT EDIT.

{optimized_code_str}

#endif // XGB_MODEL_H
"""

    # 5. Save the final C header file
    try:
        with open(OUTPUT_FILE, "w") as f:
            f.write(final_code)
        print(f"SUCCESS! Transpiled model saved to '{OUTPUT_FILE}'.")
        print("You can now resume the PlatformIO workflow (build, upload, monitor).")
    except IOError as e:
        print(f"FATAL: Could not write to '{OUTPUT_FILE}'. Please check permissions. Error: {e}")

if __name__ == '__main__':
    transpile_model()
