import xgboost
import m2cgen as m2c
import os
import sys
import sklearn
import json

# The model file is now the version-agnostic JSON format
MODEL_FILE = 'model.json'
OUTPUT_DIR = 'src'
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'xgb_model.h')

def transpile_model():
    """
    Loads a model from XGBoost's JSON format, transpiles it to C code,
    optimizes it for single-precision hardware, and saves it as a C header file.
    """
    print("--- XGBoost to C Transpilation for ESP32-S3 ---")
    print(f"  Python version: {sys.version}")
    print(f"  m2cgen version: {m2c.__version__}")
    print(f"  xgboost version: {xgboost.__version__}")
    print(f"  scikit-learn version: {sklearn.__version__}")
    print("-" * 40)

    # Ensure output directory exists
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        print(f"Created directory: '{OUTPUT_DIR}'")

    # 1. Load the model and manually set n_classes_
    print("Loading model and setting n_classes_...")
    try:
        # Load the raw booster to inspect its config
        booster = xgboost.Booster()
        booster.load_model(MODEL_FILE)
        config = json.loads(booster.save_config())
        num_class = int(config['learner']['learner_model_param']['num_class'])
        print(f"Model has {num_class} classes.")

        # Instantiate classifier, load model, and set the missing attribute
        model = xgboost.XGBClassifier()
        model.load_model(MODEL_FILE)
        model.n_classes_ = num_class
        
        print("Model loaded and configured successfully.")
    except Exception as e:
        print(f"FATAL: An error occurred while loading and configuring the model: {e}")
        return

    # 2. Transpile model to C code
    print("Transpiling model to C code...")
    try:
        model_code_str = m2c.export_to_c(model)
    except Exception as e:
        print(f"FATAL: m2cgen failed to transpile the model.")
        print(f"Error: {e}")
        return

    # 3. Hardware Optimization: Replace 'double' with 'float'
    optimized_code_str = model_code_str.replace('double', 'float')
    print("Optimized code for single-precision FPU by replacing 'double' with 'float'.")

    # 4. ESP32 Memory Optimization: Add PROGMEM and IRAM_ATTR
    # Place large constant arrays into flash memory instead of SRAM
    optimized_code_str = optimized_code_str.replace('static const float', 'static const float PROGMEM')
    optimized_code_str = optimized_code_str.replace('static const int', 'static const int PROGMEM')
    # Place the scoring function into faster IRAM
    optimized_code_str = optimized_code_str.replace('float score(', 'IRAM_ATTR float score(')
    print("Optimized for ESP32 by adding PROGMEM to arrays and IRAM_ATTR to score function.")

    # 5. Add include guard and necessary headers for safe inclusion
    final_code = f"""#ifndef XGB_MODEL_H
#define XGB_MODEL_H

// Automatically generated by m2cgen. DO NOT EDIT.
#include <pgmspace.h> // For PROGMEM support

{optimized_code_str}

#endif // XGB_MODEL_H
"""

    # 6. Save the final C header file
    try:
        with open(OUTPUT_FILE, "w") as f:
            f.write(final_code)
        print(f"SUCCESS! Transpiled model saved to '{OUTPUT_FILE}'.")
        print("You can now resume the PlatformIO workflow (build, upload, monitor).")
    except IOError as e:
        print(f"FATAL: Could not write to '{OUTPUT_FILE}'. Please check permissions. Error: {e}")

if __name__ == '__main__':
    transpile_model()
